### ISSUE TITLE
What is the correct way to enter the argument --string?

### ISSUE THREAD

**Issue by AOXE3D** [fmiotello/fastVC#2]
I have doubts about how to enter the text for the tts, I use "", '', in capital letters, in small letters, with spaces, without spaces, with hyphens between words, but I always get the same result.

`[Importing libraries...]
[Loading models...]
Traceback (most recent call last):
  File "main.py", line 133, in <module>
    raise Exception("[ERROR] Can't specify both source and string args.")
Exception: [ERROR] Can't specify both source and string args.`

**Comment by fmiotello** [comment]
If you want to manually insert the text for the TTS (excluding the ASR step) you must specify the `--string` option only, without including the `--source` option.

Hope this helps!

**Comment by AOXE3D** [comment]
thank you very much, I had the idea that I could specify the target speech by entering the --string argument, while using --source and --target. In all my tests the verbal speech was nothing similar to the source audio, do you have any idea how to improve the target phonetics?

**Comment by fmiotello** [comment]
You could try changing the `--seed` option. Other than this make sure that the source audio speech is intelligible and not noisy.
